### ISSUE TITLE
Weird glitch with EIN values fluctuating on v0.4.4 of OpenRCT2

### ISSUE THREAD

**Issue by ntfrueh** [Die4Ever/rollercoaster-tycoon-randomizer#29]
Encountered a strange issue on the latest release of OpenRCT2 where all ride EIN values were flickering constantly between various values. Attaching zipped save file for reference.

Glitch occurred while streaming - specific time discussed is linked [here](https://www.twitch.tv/videos/1790432658?t=0h42m18s)

[Fiasco Forest Randomizer Glitch.zip](https://github.com/Die4Ever/rollercoaster-tycoon-randomizer/files/11196281/Fiasco.Forest.Randomizer.Glitch.zip)

EDIT: Forgot to mention, but it was replicated both on Fiasco Forest (Corkscrew Follies pack) and African Diamond Mines (Wacky Worlds pack)

**Comment by Die4Ever** [comment]
Thanks for the bug report! Your save file made it easy to fix. You can try this alpha version, this is the only change here so far. I still want to look into some of the crowd control effects not working.

[rollercoaster-tycoon-randomizer.zip](https://github.com/Die4Ever/rollercoaster-tycoon-randomizer/files/11255796/rollercoaster-tycoon-randomizer.zip)

**Comment by Die4Ever** [comment]
Ok here's an updated version that also fixes the crowd control effects

[rollercoaster-tycoon-randomizer.zip](https://github.com/Die4Ever/rollercoaster-tycoon-randomizer/files/11256215/rollercoaster-tycoon-randomizer.zip)

**Comment by Die4Ever** [comment]
build without running cost randomization

[rollercoaster-tycoon-randomizer.zip](https://github.com/Die4Ever/rollercoaster-tycoon-randomizer/files/11257010/rollercoaster-tycoon-randomizer.zip)

**Comment by Die4Ever** [comment]
fixed running cost randomization 

[rollercoaster-tycoon-randomizer.zip](https://github.com/Die4Ever/rollercoaster-tycoon-randomizer/files/11257468/rollercoaster-tycoon-randomizer.zip)
